name: Latest Blog Post Workflow

on:
  schedule:
    # 매일 12시간마다 자동으로 실행합니다
    - cron: '0 */12 * * *'
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  update-readme-with-blog:
    name: Update this readme with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # 세현 님의 블로그 RSS 주소를 여기에 적어줍니다
          feed_list: "https://api.velog.io/rss/@tpgus72513"
